name: CI - Tests & Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Installer dépendances
        run: npm ci

      - name: Lancer les tests
        run: npm test

      - name: Build de l'application
        run: npm run build

      - name: Sauvegarder l'artefact du build
        uses: actions/upload-artifact@v4
        with:
          name: site-dist
          path: dist
